import type { MetadataRoute } from 'next';
import { listGuideSlugs, GUIDES } from '@/lib/guides';
import { SITE } from '@/lib/seo';

// Multi-sitemap split using Next.js 15's generateSitemaps.
//
// Output URLs:
//   /sitemap.xml             ← sitemap index (auto-generated by Next.js)
//   /sitemap/0.xml           ← core pages
//   /sitemap/1.xml           ← platform downloaders
//   /sitemap/2.xml           ← guides (long-form articles)
//   /sitemap/3.xml           ← legal pages
//
// Splitting by content type is the SEO-veteran move because:
// 1. Google's crawl budget is finite — separate sub-sitemaps let it
//    re-crawl high-velocity sections (guides) without re-fetching the
//    entire sitemap.
// 2. Each sub-sitemap can carry domain-appropriate <image:> or
//    <video:> extensions without polluting unrelated entries.
// 3. The 50K-URL ceiling per sitemap stops being a problem if the site
//    ever scales to that size.

export async function generateSitemaps() {
  return [
    { id: 0 }, // core
    { id: 1 }, // platforms
    { id: 2 }, // guides
    { id: 3 }, // legal
  ];
}

interface Entry {
  path: string;
  priority: number;
  changeFrequency: 'daily' | 'weekly' | 'monthly';
  title: string;
  lastModified?: Date;
}

const ogImage = (title: string): string =>
  `${SITE.url}/og?title=${encodeURIComponent(title.slice(0, 80))}`;

function toSitemapEntry(e: Entry): MetadataRoute.Sitemap[number] {
  return {
    url: `${SITE.url}${e.path}`,
    lastModified: e.lastModified ?? new Date(),
    changeFrequency: e.changeFrequency,
    priority: e.priority,
    images: [ogImage(e.title)],
  };
}

export default async function sitemap({ id }: { id: number }): Promise<MetadataRoute.Sitemap> {
  switch (id) {
    case 0: {
      const entries: Entry[] = [
        { path: '/', priority: 1, changeFrequency: 'daily', title: 'Save47 — Free Video Downloader' },
        { path: '/all-platforms', priority: 0.95, changeFrequency: 'weekly', title: 'All Supported Platforms' },
        { path: '/online-video-downloader', priority: 0.9, changeFrequency: 'weekly', title: 'Online Video Downloader' },
        { path: '/free-video-downloader', priority: 0.9, changeFrequency: 'weekly', title: 'Free Video Downloader' },
        { path: '/hd-video-downloader', priority: 0.9, changeFrequency: 'weekly', title: 'HD Video Downloader' },
        { path: '/api', priority: 0.9, changeFrequency: 'weekly', title: 'Save47 API & CLI' },
        { path: '/pricing', priority: 0.9, changeFrequency: 'weekly', title: 'Pricing' },
        { path: '/download/apk', priority: 0.9, changeFrequency: 'weekly', title: 'Save47 Android APK' },
        { path: '/compare', priority: 0.85, changeFrequency: 'monthly', title: 'Save47 vs other downloaders' },
        { path: '/guides', priority: 0.85, changeFrequency: 'weekly', title: 'Video Downloader Guides' },
      ];
      return entries.map(toSitemapEntry);
    }

    case 1: {
      const entries: Entry[] = [
        { path: '/youtube-downloader', title: 'YouTube Video Downloader', priority: 0.85, changeFrequency: 'weekly' },
        { path: '/youtube-mp4-downloader', title: 'YouTube to MP4 Downloader', priority: 0.85, changeFrequency: 'weekly' },
        { path: '/youtube-to-mp3', title: 'YouTube to MP3 Converter', priority: 0.85, changeFrequency: 'weekly' },
        { path: '/youtube-shorts-downloader', title: 'YouTube Shorts Downloader', priority: 0.85, changeFrequency: 'weekly' },
        { path: '/instagram-reel-downloader', title: 'Instagram Reel Downloader', priority: 0.85, changeFrequency: 'weekly' },
        { path: '/instagram-video-downloader', title: 'Instagram Video Downloader', priority: 0.85, changeFrequency: 'weekly' },
        { path: '/tiktok-downloader', title: 'TikTok Video Downloader', priority: 0.85, changeFrequency: 'weekly' },
        { path: '/facebook-video-downloader', title: 'Facebook Video Downloader', priority: 0.85, changeFrequency: 'weekly' },
        { path: '/twitter-video-downloader', title: 'Twitter / X Video Downloader', priority: 0.85, changeFrequency: 'weekly' },
        { path: '/reddit-video-downloader', title: 'Reddit Video Downloader', priority: 0.85, changeFrequency: 'weekly' },
        { path: '/soundcloud-downloader', title: 'SoundCloud to MP3 Downloader', priority: 0.85, changeFrequency: 'weekly' },
        { path: '/pinterest-video-downloader', title: 'Pinterest Video Downloader', priority: 0.85, changeFrequency: 'weekly' },
        { path: '/vimeo-downloader', title: 'Vimeo Video Downloader', priority: 0.85, changeFrequency: 'weekly' },
        { path: '/twitch-clip-downloader', title: 'Twitch Clip Downloader', priority: 0.85, changeFrequency: 'weekly' },
        { path: '/dailymotion-downloader', title: 'Dailymotion Video Downloader', priority: 0.85, changeFrequency: 'weekly' },
      ];
      return entries.map(toSitemapEntry);
    }

    case 2: {
      const entries: Entry[] = listGuideSlugs().map((slug) => {
        const g = GUIDES.find((x) => x.slug === slug)!;
        return {
          path: `/guides/${slug}`,
          priority: 0.7,
          changeFrequency: 'monthly',
          title: g.title,
          lastModified: new Date(g.updatedAt),
        };
      });
      return entries.map(toSitemapEntry);
    }

    case 3: {
      const entries: Entry[] = [
        { path: '/terms', title: 'Terms of Use', priority: 0.3, changeFrequency: 'monthly' },
        { path: '/privacy', title: 'Privacy Policy', priority: 0.3, changeFrequency: 'monthly' },
        { path: '/dmca', title: 'DMCA Policy', priority: 0.3, changeFrequency: 'monthly' },
      ];
      return entries.map(toSitemapEntry);
    }

    default:
      return [];
  }
}
